//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aptitude_Test
    {
        public int Aptitude_Test_id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Branch_id { get; set; }
    }
}
