//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companycriteria
    {
        public int Companycriteriaid { get; set; }
        public Nullable<decimal> Min_CGPA { get; set; }
        public decimal Min_Spi { get; set; }
        public int Max_Backlogs { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<decimal> std10PR { get; set; }
        public Nullable<decimal> std12PR { get; set; }
        public string Branchname { get; set; }
    }
}
