//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBranch
    {
        public int CompanyBranchId { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
