//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SvitTrainingPlacementEntities : DbContext
    {
        public SvitTrainingPlacementEntities()
            : base("name=SvitTrainingPlacementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CompanyBranch> CompanyBranches { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<coordinator> coordinators { get; set; }
        public virtual DbSet<Companycriteria> Companycriterias { get; set; }
        public virtual DbSet<Aptitude_Test> Aptitude_Test { get; set; }
        public virtual DbSet<Placedstudent> Placedstudents { get; set; }
    
        public virtual ObjectResult<CompanyInfoselectAll_Result> CompanyInfoselectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CompanyInfoselectAll_Result>("CompanyInfoselectAll");
        }
    }
}
