//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placedstudent
    {
        public long intstudentid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int companyid { get; set; }
        public int Branchid { get; set; }
        public string Enrollment { get; set; }
    }
}
