//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvitTrainingAndPlacementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int intUserid { get; set; }
        public string strPassword { get; set; }
        public string strFirstname { get; set; }
        public string strLastname { get; set; }
        public string strEmail { get; set; }
        public Nullable<int> intGender { get; set; }
        public string strResidency { get; set; }
        public Nullable<int> intUserType { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<System.DateTime> datCreateddate { get; set; }
        public Nullable<int> intModifiedby { get; set; }
        public Nullable<System.DateTime> datModifieddate { get; set; }
    }
}
